### ISSUE TITLE
wrong Chinese translation

### ISSUE THREAD

**Issue by yuanmu97** [maxwellito/breaklock#14]
The translated explanations of dots are wrong:
the white dot's text "位置正确但顺序错误" means "in the pattern but in the wrong order", which should be the text for the black dot.

**Comment by maxwellito** [comment]
Hi,

Thanks for spotting the problem and taking the time to open an issue. Do
you think you could make a PR to
https://github.com/maxwellito/breaklock/blob/main/src/l10n/zh.yml ? I'll
merge it once I get access back to my laptop.

Also, do you recommend any translation for "Continue", "New_game" and
"Back_home"? I realised that the game over screen isn't translated.

Many thanks,
- Max

**Comment by yuanmu97** [comment]
Hi, I just made a PR.
I recommend "继续" for "Continue", "新游戏" for "New Game", and "返回" for "Back Home".

Very fun game! Although my iphone does not support this kind of unlocking :)

**Comment by maxwellito** [comment]
Thank you so much! I will fix the code this weekend to include your
suggestions and merge your PR.
Thanks for your help, and glad you like the game :)

**Comment by maxwellito** [comment]
Thanks again for your PR and your translations :)
