### ISSUE TITLE
no description

### ISSUE THREAD

**Issue by nstringham** [maxwellito/breaklock#6]
I am making an app which catalogues PWAs but your app doesn't have a description. Could you please add a `<meta name="description"/>` tag or the `"description"` property in the web app manifest. I would be willing to make a PR if you want me to.

**Comment by maxwellito** [comment]
Sure :) Any description ideas? How long should it be?

**Comment by nstringham** [comment]
here is some guidlines from google for what to put in a description meta tag https://developers.google.com/search/docs/advanced/appearance/good-titles-snippets#meta-descriptions

there isn't yet a standard for web app descriptions but you can check out [Apple's guidance for app store descriptions](https://developer.apple.com/app-store/product-page/) that should be pretty similar.

I would suggest "A puzzle game hybrid of Mastermind and the Android pattern lock." It's kinda short but it's a relatively simple app so it doesn't take much to describe it

**Comment by nstringham** [comment]
oops didn't mean to close it

**Comment by maxwellito** [comment]
It should be fixed by now :)
There was already a description in the i10n. I hope it solves your problem.

If your PWA catalog is public I would love to have a look. Feel free to share the URL

**Comment by nstringham** [comment]
> It should be fixed by now :)

yep it works now thanks :)


> If your PWA catalog is public I would love to have a look. Feel free to share the URL

We are still under development but the plan is to go public and I'll try to remember to share it here when we do

**Comment by nstringham** [comment]
> If your PWA catalog is public I would love to have a look. Feel free to share the URL

@maxwellito We have make a minimum viable product publicly available for web app gallery you can check it out at https://webappgallery.trev.xyz
